### ISSUE TITLE
MADAMIRA keeps dying

### ISSUE THREAD

**Issue by reynoldsnlp** [reynoldsnlp/flair#16]
Figure out why, and maybe we need to integrate into systemd, i.e. turn it into a service.

**Comment by mjbriggs** [comment]
While I have not done work on this specific issue since I do not persistently run the Madamira server in my development environment. One potential fix for this issue could be the implementation of docker when we host our sites. As I currently have it set up, there is a container for flair and a container for madamira, which communicate on a network called flair-net. You would have to create this network on the deployment server. [Documentation on docker network commands can be found here](https://docs.docker.com/engine/reference/commandline/network/). Since both servers would run with docker, they would be as persistent as you want them to be.
